In [10]:
import numpy as ag


In [11]:
a=ag.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
b=ag.array([[1],[2],[3],[4]])
print(b)

[[1]
 [2]
 [3]
 [4]]


In [15]:
c=ag.hstack((a,b))
print(c)

ValueError: all the input arrays must have same number of dimensions

In [7]:
c=ag.array([[1,2,3],[2,3,4]])
print(c)

[[1 2 3]
 [2 3 4]]


In [14]:
print(a.shape)
print(b.shape)
print(b[2][0])
print(c.shape)
print(c[1][2])

(4,)
(4, 1)
3
(2, 3)
4


In [16]:
d=ag.zeros((5,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
e=5*ag.ones((5,5))+4
print(e)
f=ag.hstack((d,e))
print(f)
s=ag.vstack((d,e))
print(s)


[[9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]]
[[0. 0. 0. 0. 0. 9. 9. 9. 9. 9.]
 [0. 0. 0. 0. 0. 9. 9. 9. 9. 9.]
 [0. 0. 0. 0. 0. 9. 9. 9. 9. 9.]
 [0. 0. 0. 0. 0. 9. 9. 9. 9. 9.]
 [0. 0. 0. 0. 0. 9. 9. 9. 9. 9.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9.]]


In [24]:
e[1:3,2:4]=100
print(e)

[[  9.   9.   9.   9.   9.]
 [  9.   9. 100. 100.   9.]
 [  9.   9. 100. 100.   9.]
 [  9.   9.   9.   9.   9.]
 [  9.   9.   9.   9.   9.]]


In [23]:
c[1][1]=100
print(c)

[[  1   2   3]
 [  2 100   4]]


In [3]:
f=ag.full((4,5),7)
print(f)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [4]:
f[2:3,2:4]=30
print(f)

[[ 7  7  7  7  7]
 [ 7  7  7  7  7]
 [ 7  7 30 30  7]
 [ 7  7  7  7  7]]


In [5]:
f[1:2,2:3]=100
print(f)

[[  7   7   7   7   7]
 [  7   7 100   7   7]
 [  7   7  30  30   7]
 [  7   7   7   7   7]]


In [6]:
print(f[1:3,2:4])

[[100   7]
 [ 30  30]]


In [13]:
h=6*ag.eye(5)+6-3
print(h)

[[9. 3. 3. 3. 3.]
 [3. 9. 3. 3. 3.]
 [3. 3. 9. 3. 3.]
 [3. 3. 3. 9. 3.]
 [3. 3. 3. 3. 9.]]


In [7]:
k=ag.random.random((2,4))
print(k)

[[0.64079561 0.97465832 0.48185968 0.09133746]
 [0.82458666 0.13123838 0.8561435  0.35235094]]


In [8]:
print(k[:,1])

[0.97465832 0.13123838]


In [53]:
g=ag.zeros((3,4),dtype=ag.int64)
print(g)
g[2,1:3]=7
g[:,2]=6
print(g)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 6 0]
 [0 0 6 0]
 [0 7 6 0]]


In [55]:
print(type(a),a.dtype)
print(type(b),b.dtype)
print(type(c),g.dtype)
print(type(k),k.dtype)

<class 'numpy.ndarray'> int32
<class 'numpy.ndarray'> int32
<class 'numpy.ndarray'> int64
<class 'numpy.ndarray'> float64


In [57]:
x=ag.array([[2,3,4],[3,4,5]])+ag.array([[3,4,5],[3,4,5]])
print(x)

[[ 5  7  9]
 [ 6  8 10]]


In [59]:
h=ag.random.randint(1,30,(5,5))
print(h)

[[16 18 19 11  8]
 [19 18 24  7 23]
 [21 22 15 18 21]
 [ 2 17 16 18 14]
 [27 18 26 14 11]]


In [62]:
print(ag.sum(h))

423


In [65]:
print(ag.min(h))
print(ag.max(h))
print(ag.mean(h))

2
27
16.92


In [69]:
print(ag.arange(1,8))


[1 2 3 4 5 6 7]


In [21]:
alk=ag.random.random((2,4))
print(alk)

[[0.56946802 0.53697608 0.56062131 0.0923277 ]
 [0.38295216 0.67199362 0.84376182 0.60014381]]


In [9]:
h=h.reshpae(6,1)

NameError: name 'h' is not defined

In [27]:
f=ag.full((4,5),6)
print(f)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [37]:
ik=ag.eye(5)
print(ik)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
print(ag.max(alk))
print(ag.min(alk))
print(ag.mean(alk))
print(ag.average(alk))

0.8437618155146267
0.09232770107797783
0.53228056652911
0.53228056652911


In [47]:
print(ag.add(h,ik))
print(h+ik)
print(sum(h))
print(h-ik)
print(ag.multiply(h,ik))
print(ag.divide(h,ik))

[[10.  3.  3.  3.  3.]
 [ 3. 10.  3.  3.  3.]
 [ 3.  3. 10.  3.  3.]
 [ 3.  3.  3. 10.  3.]
 [ 3.  3.  3.  3. 10.]]
[[10.  3.  3.  3.  3.]
 [ 3. 10.  3.  3.  3.]
 [ 3.  3. 10.  3.  3.]
 [ 3.  3.  3. 10.  3.]
 [ 3.  3.  3.  3. 10.]]
[21. 21. 21. 21. 21.]
[[8. 3. 3. 3. 3.]
 [3. 8. 3. 3. 3.]
 [3. 3. 8. 3. 3.]
 [3. 3. 3. 8. 3.]
 [3. 3. 3. 3. 8.]]
[[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]
[[ 9. inf inf inf inf]
 [inf  9. inf inf inf]
 [inf inf  9. inf inf]
 [inf inf inf  9. inf]
 [inf inf inf inf  9.]]


c:\new folder\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [52]:
g=ag.array([[1,2,3,4],[2,34,5,6],[6,7,8,9]])
print(g)

[[ 1  2  3  4]
 [ 2 34  5  6]
 [ 6  7  8  9]]


In [54]:
ag.random.shuffle(g)
print(g)

[[ 2 34  5  6]
 [ 1  2  3  4]
 [ 6  7  8  9]]


In [61]:
print(ag.max(g,axis=1))
print(ag.mean(g,axis=1))

[34  4  9]
[11.75  2.5   7.5 ]


In [2]:
g=ag.full((2,2),2)
k=ag.full((2,2),2)
print(ag.dot(g,k))

[[8 8]
 [8 8]]
