In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dfx=pd.read_csv("Logistic_X_Train.csv").values
dfy=pd.read_csv("Logistic_Y_Train.csv").values
dft=pd.read_csv("Logistic_X_Test.csv").values

In [3]:
print(dfx)

[[-1.23937466  0.74910149 -0.52851491]
 [-1.03607028  0.80143631 -1.28371152]
 [-0.61557914  1.57952053 -1.39192706]
 ...
 [ 0.08827657  1.63878904 -2.19364056]
 [ 1.52515501  0.85923429  1.50530791]
 [-0.97981744  0.56395376 -1.53939416]]


In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
lr=LogisticRegression()

In [6]:
lr.fit(dfx,dfy)

c:\new folder\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\new folder\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [7]:
lr.coef_

array([[-3.68470635,  2.8811019 , -2.24745975]])

In [8]:
lr.intercept_
lr.score(dfx,dfy)

0.995

In [9]:
test=lr.predict(dft)

In [10]:
np.savetxt("f20.csv", test, delimiter=",")