In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
mean_01=np.array([1.,0.5])
cov_01=np.array([[1,0.1],[0.1,0.4]])

mean_02=np.array([5,5.5])
cov_02=np.array([[1.2,0.1],[0.1,0.3]])

In [36]:
dist_01=np.random.multivariate_normal(mean_01,cov_01,400)
dist_02=np.random.multivariate_normal(mean_02,cov_02,400)

In [37]:
total=800

In [38]:
np.random.shuffle(data)

In [39]:
u=np.mean(data[:,:-1],axis=0)
sigma=np.std(data[:,:-1],axis=0)
data=(data[:,:-1]-u)/sigma
print(data.shape)

(800, 2)


In [40]:
ones=np.ones((data.shape[0],1),dtype='float32')
final_data=np.hstack((ones,data))
print(final_data)

[[ 1.          1.03108557  1.14276182]
 [ 1.         -0.63234338 -0.60332852]
 [ 1.         -1.09391456 -1.13838728]
 ...
 [ 1.         -0.46873707 -0.82759497]
 [ 1.         -0.86229554 -0.81349022]
 [ 1.         -1.27270342 -1.14157353]]


In [41]:
data=np.zeros((800,3))

In [42]:
data[:400,:-1]=dist_01
data[400:,:-1]=dist_02
data[400:,-1]=1

In [43]:
split=int(0.8*total)
print(split)

640


In [44]:
x_train=final_data[:split,:-1]
x_test=final_data[split:,:-1]

y_train=final_data[:split,:-1]
y_test=final_data[split:,:-1]

In [45]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(640, 2) (160, 2)
(640, 2) (160, 2)


In [50]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [52]:
def hypothesis(x,theta):
    return sigmoid(np.dot(x,theta))

In [55]:
def error(Y,X,theta):
    m=x.shape[0]
    total_error=0
    for i in range(m):
        y_hat-hypotheis(X[i],theta)
        total_error+=-(Y[i]*np.log2(y_hat)+(1-Y[i])*np.log2(1-y_hat))
    return total_error/m

In [59]:
def get_grad(Y,X,theta):
    grad=np.zeros(theta.shape)
    m=x.shape[0]
    for i in range(m):
        y_hat=hypothesis(X[i],theta)
        x=grad+=(Y[i]-y_hat)*x
    return grad/m

SyntaxError: invalid syntax (<ipython-input-59-29337591e04f>, line 6)

In [60]:
def grad_descent(X,Y,learning_rate=0.1):
    theta=np.zeros((X.shape[1],1))
    error_list=[]
    for i in range(50):
        theta=theta-learning_rate*get_grad(X,Y,theta)
        e=error(Y,X,theta)
        error_list.append